# Generated by Django 4.0.6 on 2022-08-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان در url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/logo', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال شده / نشده')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی کتاب',
                'verbose_name_plural': 'دسته بندی کتاب ها',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان در url')),
                ('writer', models.CharField(max_length=200, verbose_name='نویسنده')),
                ('translator', models.CharField(blank=True, max_length=200, null=True, verbose_name='مترجم')),
                ('image', models.ImageField(upload_to='images/books', verbose_name='تصویر')),
                ('file', models.FileField(upload_to='files/books', verbose_name='فایل')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='بها')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('category', models.ManyToManyField(related_name='book_category', to='books_module.bookcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
    ]
