# Generated by Django 4.0.6 on 2022-08-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='submit_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت'),
        ),
    ]
