# Generated by Django 4.0.6 on 2022-08-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0002_books_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='submit_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
