# Generated by Django 4.0.6 on 2022-10-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0013_alter_bookcomments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomments',
            name='user',
        ),
        migrations.AddField(
            model_name='bookcomments',
            name='user_email',
            field=models.CharField(blank=True, default=False, max_length=200, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='bookcomments',
            name='user_name',
            field=models.CharField(blank=True, default=False, max_length=200, null=True, verbose_name='نام'),
        ),
    ]
