# Generated by Django 4.0.6 on 2022-10-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0014_remove_bookcomments_user_bookcomments_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomments',
            name='user_email',
        ),
        migrations.AlterField(
            model_name='bookcomments',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام'),
        ),
    ]
