# Generated by Django 4.0.6 on 2022-10-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0016_remove_bookcomments_user_name_bookcomments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_module.bookcomments', verbose_name='والد'),
        ),
    ]
