# Generated by Django 4.0.6 on 2022-10-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0017_bookcomments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomments',
            name='parent',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_module.bookcomments', verbose_name='والد'),
        ),
    ]
