# Generated by Django 4.0.6 on 2022-10-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0018_alter_bookcomments_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomments',
            name='parent',
        ),
    ]
