# Generated by Django 4.0.6 on 2022-10-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0019_remove_bookcomments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomments',
            name='submit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت'),
        ),
    ]
