# Generated by Django 4.0.6 on 2022-10-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0020_alter_bookcomments_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_module.bookcomments', verbose_name='والد'),
        ),
    ]
