# Generated by Django 4.0.6 on 2022-11-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0021_bookcomments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomments',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comment', to='books_module.books', verbose_name='کتاب'),
        ),
    ]
