# Generated by Django 4.0.6 on 2022-12-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0022_alter_bookcomments_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
