# Generated by Django 4.0.6 on 2022-12-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetting_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteLocationMap',
        ),
    ]
