# Generated by Django 4.0.6 on 2022-11-12 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books_module', '0021_bookcomments_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('url_title', models.CharField(max_length=250, verbose_name='عنوان در url')),
                ('about', models.TextField(verbose_name='درباره')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/writers', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال شده/نشده')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده/نشده')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_writer', to='books_module.books', verbose_name='نویسنده ی کتاب')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
    ]
