# Generated by Django 4.0.6 on 2022-11-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0021_bookcomments_parent'),
        ('writers_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writers',
            name='book',
        ),
        migrations.AddField(
            model_name='writers',
            name='book',
            field=models.ManyToManyField(related_name='book_writer', to='books_module.books', verbose_name='نویسنده ی کتاب'),
        ),
    ]
