# Generated by Django 4.0.6 on 2022-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_about_user_alter_user_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, verbose_name='ایمیل')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'عضو خبرنامه',
                'verbose_name_plural': 'اعضای خبرنامه',
            },
        ),
    ]
